### ISSUE TITLE
session.cookie.idletime does not work with redis storage

### ISSUE THREAD

**Issue by thorstenfleischmann** [bungle/lua-resty-session#123]
I tried using session.cookie.idletime together with redis and regenerate strategy. After [one minute](https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session.lua#L283) the cookie "stops" working as expected. The browser receives a new cookie (same id, different "use before", different hash) and the subsequent requests can not use the session anymore.

I added some logging here: https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session.lua#L598

err is "unable to decrypt data". It seems to me that the encrypted data is not updated with the latest "usebefore"-value since usebefore is also used as a key for encryption: 

https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session/strategies/default.lua#L97

btw: thanks for this awesome library

**Comment by bungle** [comment]
@thorstenfleischmann, thank you for reporting. Need to be fixed.

**Comment by JakeEmo** [comment]
I am having the exact same issue using the Kong (API Gateway) session plugin that uses this library. I use the Kong storage option which uses the regenerate strategy, and I get the exact same behavior as desribed above, I will try to display my digging in where I believe the issue could come from, but I dont really know a fix
If any value is used for idletime, after 60 seconds of establishing a session, set-cookie comes back with a new session, however upon looking through the code, it seems to be based on this calculation
https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session.lua#L283
which would return true in this setup I believe after the new/old difference is greater than 60 (seconds)
This makes a "touch" operation happen, and a set_cookie happen, however when i looked at the touch, it does not save the new cookie to the database (like a save does), so when the client uses the latest cookie, it is not valid (authentication fails)

so to me maybe the touch should not change the cookie, but should only be maintained as an internal timer, or a touch should only happen if the idletime is hit (not 60 seconds), I will try to work on a PR but i'm still a little confused on the implementation.

**Comment by JakeEmo** [comment]
I wanted to add another comment to act as a sounding board for how I understand what the idletime logic is trying to accomplish
versus renew or lifetime, the idletime is a dynamic timer, and at the end of the day needs to be stored in the DB in this storage method, I think what is happening here is that the cookie changes because the "usebefore" is updated (right now every 60 seconds, but even if it was based on idletime, the usebefore value still needs to track the idletimer value, which is stored in the cookie/DB, the problem is if the cookie changes, it needs to be saved else its invalid in this current logic (with a touch that changes the cookie but does not save it). So how do we manage a cookie that incorporates the usebefore/idletime without it changing? I dont think you can securely, so that leaves us with storing the timer data outside the cookie, but somehow able to be looked up in relation to a given session cookie.
That way idletime can be updated per request, but the session cookie wont change until that idletime is detected OR renew/lifetime is detected.

**Comment by JakeEmo** [comment]
Following up after more digging, I realized that if you select the cookie storage option, the idletime logic seems to work fine, and the cookie remains valid, so i thought "what is different between the two strategies?" after investigating the touch logic between the default and regenerate strategies, the regenerate passes a different concatenated key into the modify function here
https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session/strategies/regenerate.lua#L24
which makes it bypass the normal processing/concatenation of the string here
https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session/strategies/default.lua#L97
So what I cant understand if the purpose of the key function here, that seems to omit the expires data?
https://github.com/bungle/lua-resty-session/blob/2cd1f8484fdd429505ac33abf7a44adda1f367bf/lib/resty/session/strategies/regenerate.lua#L13
They both pivot/use the session object, so I dont know why regenerate doesnt use the same touch as default.
Hope this helps

**Comment by bungle** [comment]
@JakeEmo thanks for info, I'll try to fix this within a week
