### ISSUE TITLE
problems with using shm storage

### ISSUE THREAD

**Issue by d80x86** [bungle/lua-resty-session#127]
centos 7
openresty - 1.19.3.2
lua-resty-session - 3.8

nginx.conf
```
lua_shared_dict sessions    10m;
```

test.lua
``` lua
local opts = {
   storage = 'shm',
   shm = { store = 'sessions' }
 }

 local ses = require 'resty.session'.start(opts)
 ses.data.v = 'ccav'
 ses:save()

 ngx.print('ok')
```

'OK' is correct only the first time
The second time: throw error attempt to index local 'ses' (a nil value)
The third time: hang up until timeout(5 second), and print 'OK'

subsequent result:  throw error -> hang up -> throw error -> hang up .....

**Comment by yunzhiyi** [comment]
I meet the same issue: ### The second time: throw error attempt to index local 'ses' (a nil value)
I think the root cause is that:
1. session.start(opts) -> session.open(opts, true) -> self.strategy.open(self, cookie, true) will lock the shm,
2. then session.start -> self.strategy.start(self) want to lock the shm again, and lua-resty-lock.lock() return error "locked", and session.start return nil, "locked"

https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L615

`function session.open(opts, keep_lock)
...
    local err
    local cookie = self:get_cookie()
    if cookie then
        cookie, err = self:parse_cookie(cookie)
        if cookie then
            local ok
            ok, err = self.strategy.open(self, cookie, keep_lock)
            if ok then
                return self, true
            end
        end
    end
...
end

function session.start(opts)
...
    local self, present, reason = session.open(opts, true)
...
    if self.strategy.start then
        local ok, err = self.strategy.start(self)
        if not ok then
            return nil, err or "unable to start session"
        end
    end
...
end`

**Comment by d80x86** [comment]
Yes, using session.open() is fine
However, calling session.start() directly is problematic, and will be locked until timeout.
Normally, after session.save() is called, locked should be turned off.
