### ISSUE TITLE
Attempt to perform arithmetic on field 'size' (a nil value)

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [bungle/lua-resty-session#18]
https://github.com/bungle/lua-resty-session/blob/fbc1057331046c6a625255d8a281c4b9335a7a36/lib/resty/session.lua#L132

Happens when ``$session_secret`` is not set in nginx.

**Comment by bungle** [comment]
Great catch!

**Comment by bungle** [comment]
Fixed in 2.2. Now that we have pluggable ciphers we don't really care about the size of the secret. Ciphers should derive their own keys from secret string that can be anything. I had to remove all the session_cipher_* configs, they don't belong to session anymore. Ciphers have their own configuration that they take care independently. The default secret size is now 32 bytes of random data and it is not configurable.
