### ISSUE TITLE
Question about $session_cookie_renew

### ISSUE THREAD

**Issue by vstath** [bungle/lua-resty-session#44]
Hello,

I am not sure about the situation so I thought about asking the author. 

I am testing your library with Redis storage. I understand that $session_cookie_lifetime translates into Redis TTL expiry for the key (and this is what I want). 

I am not sure where the $session_cookie_renew fits in this. Reading the manual it mentions about renewing the TTL of the cookie. 

From what I see, on each "open" request, the Redis TTL of the session is updated to my $session_cookie_lifetime (as expected also since if the user has come back, I want his session to extend).

Since I'm using session cookies (ie the default of the library) with a lifetime of browser being open, is renew really used for the cookie? Or only the Redis TTL is honored (which is what I need actually)? I'm a little confused whether my understanding is correct in this particular scenario. 

What I understand *for my specific scenario* is: the browser cookie does not expire so $session_cookie_renew is not applicable. The session expires when the key is removed from Redis (on TTL or destroy session). The browser cookie will be removed when browser is closed. If session is removed from Redis then the cookie will remain but session is invalid - ie I have to trap it in my code and do "start/save" for a new session.

Can you please clarify? Probably I'm reading things and the code wrong so please verify or correct my assumptions and my question.

Thanks

**Comment by bungle** [comment]
`$session_cookie_renew´ this is used only to control when the cookie is send back to the client. It is only used when you call `session:start()`. If you ever end up calling e.g. `session:save()` a new cookie is sent back to client. Cookie stores expiry date also in cookie data. It is just a really small optimization, e.g. use case:

1. User needs to login
2. User sends username and password
3. Server validates them and then sends back a session cookie where in data is `user_id`.
4. Now user can browse site as long as he wants, and each time when new request comes in server figures out that he is using valid session and he is this `user_id`. The session is rarely (or never) modified during the logged in session.
5. But there is already this lifetime in cookie (even if the cookie itself has no expiry in cookie flags, as it doesn't if you don't persist them, as you usually don't with session cookies)

The only issue with this is that if user continues to browse the site longer than the cookie lifetime (stored in cookie data). Some options:

1. send a new cookie back each time when a new request comes (e.g. not really needed if the session is not going to expire soon, so let's try to optimize that. it is configurable though)
2. do not store session lifetime in cookie data (works ok, when storing session data in server, such as redis, but not so much when storing session data in a cookie) (yes, we could have the library behave differently in such scenarios, but it is not really worth it).

No matter what, we honor both TTLs, the cookie and the server. If any of TTLs is not valid, we don't have a session.

The only place where this renew thing is used is here:
https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L337-L342

As you can see, we call `save` if the cookie we got back is going to be expired in `$session_cookie_renew` time frame. It also corrects cookies that have too far expiry time (e.g. if you have changed settings since the cookies were delivered). So in general, the flow is:

1. login
2. session.start()
3. session.data.uid = xxx; session:save()
4. request next page
5. session:start()
6. request next page
7. session:start()
...
now the session is about to expire soonish
...
37. request next page
38. session:start() (implicitly calls also  session:save())
39. goto 4

And that's about it.

If you hate this option, then set it to same as or bigger as `$session_cookie_lifetime`, then `session:start()` will always send a new cookie back whenever you call it. `session:open` will never send cookie back. You can always just use `session:open` and `session:save` manually, and never call `start`, then that option will not do anything.

This library has thee constructors:

1. session.new (just creates a session, but does not try to attach to existing one) and does not send anything back to the client (e.g. a new cookie)
2. session.open (as above, but tries to attach to existing session, still does not send anything to client, guranteed)
3. session.start (as above, but also sends a new cookie back if it is about to expire, or if the current expiry date is too far a way in a future regarding to current `lifetime` setting.

Other methods, such as:

1. `session:regenerate()`
2. `session:save()`
3. `session:destroy()`

will always send back a new cookie.

`session:hide()` is useful if you reverse proxy to some other backend, so you can actually clear up the client session cookie, so that it does not get proxied to backend (or upstream) service.

**Comment by bungle** [comment]
And whenever this library sends a cookie back to client, it will contain a expiry time of the `lifetime` (and at that point, also the server side storage is updated to same `lifetime`). e.g. `session:save()` will always update the cookie lifetime as well to full lifetime.

**Comment by bungle** [comment]
The only thing to notice though, it that If use have `renew` set to 5 min and `lifetime` set to 60 min, then when user starts a session, it will get a cookie which lifetime is 60 secs. If user makes a request at say 54 min after it was started (and you always call `start`), then the session is not renewed with new lifetime, and if user does not make a new request in 5 minutes, the session will expire :-).

**Comment by altexy** [comment]
>  it will get a cookie which lifetime is 60 secs
Do you mean 60 minutes?

**Comment by bungle** [comment]
@altexy thanks for correcting me.

**Comment by vstath** [comment]
Thank you very much for the clarification (and big thanks for the library)
