### ISSUE TITLE
Cookies are always not "secure"

### ISSUE THREAD

**Issue by vladimir-smirnov-sociomantic** [bungle/lua-resty-session#5]
Hi,

I've got some problems (maybe related to my setup, not to the plugin), but even when using server with ssl, session cookies don't have "Secure" flag (ngx.var.ssl_session_id is always nil).

I've tried Nginx both 1.6.2 and 1.7.7 with lua-nginx-module 0.9.12 and 0.9.13 installed.  ngx_devel_kit is latest 0.2.19.

**Comment by mingfang** [comment]
I'm experience similar symptoms.
Things seem to work most of the time but occasionally the session will get invalidated without reason.
The problem seems to be trigger under slightly higher load, basically hitting refresh button quickly.

My nginx.conf looks similar to this
https://github.com/mingfang/docker-knginx/blob/master/etc/confd/templates/kubernetes.conf.tmpl
This  is a confd file so you can ignore the brackets.

The resty-session specific confs are here 
https://github.com/mingfang/docker-knginx/blob/master/saml/saml.conf

This is my basic SAML implementation.
I use access_by_lua to call this https://github.com/mingfang/docker-knginx/blob/master/saml/saml.lua#L14 on every request.
The problem is sometimes the result of open() is empty when it shouldn't be.

What is the official solution/workaround?
