### ISSUE TITLE
Consider not checking TLS session ID by default

### ISSUE THREAD

**Issue by jedsmith** [bungle/lua-resty-session#9]
I just lost a couple hours to debugging why my sessions would suddenly fail to decrypt, sometimes a few seconds after starting the server, sometimes 10 minutes later, with no logging output about why. I had to disable `$session_check_ssi`.

I think there's a strong case to be made for that not to be the default. Some of the other checks are suspicious, too, like the `remote_addr` one (clients do rehome), but `$session_check_ssi` was definitely a big burden until I realized what was going on.

Can you consider logging when `$session_check_ssi` fails, or default to not doing it at all? Thanks!

**Comment by bungle** [comment]
Checking remote address is disabled by default. The changing SSL session id might also have something to do with your SSL configs (and when using session tickets, it will always be `nil`). Yes, we can add logging to the library for various purposes. But there is currently no way to determine that decrypting or mac check fails because of changed SSL Session ID. Yes, we might remove session id check by default (it is usually non-effective setting, because most of use run the servers with TLS tickets these days).

**Comment by mingfang** [comment]
I'm experiencing similar symptoms.

Things seem to work most of the time but occasionally the session will get invalidated without reason.
The problem seems to be trigger under slightly higher load, basically hitting refresh button quickly.

My nginx.conf looks similar to this
https://github.com/mingfang/docker-knginx/blob/master/etc/confd/templates/kubernetes.conf.tmpl
This is a confd file so you can ignore the brackets.

The resty-session specific confs are here 
https://github.com/mingfang/docker-knginx/blob/master/saml/saml.conf

This is my basic SAML implementation.
I use access_by_lua to call this https://github.com/mingfang/docker-knginx/blob/master/saml/saml.lua#L14 on every request.
The problem is sometimes the result of open() is empty when it shouldn't be.

**Comment by bungle** [comment]
@mingfang does the problem go away if you disable this:

```nginx
set $session_check_ssi off;
```

Because otherwise this shouldn't be related to this #9. Also do you ever call `save`? Could it be just that the client side cookie has expired? Open only opens but doesn't check if the client side cookie is about to expire. There is no automatic handle in OpenResty where we could attach to automatically send a new cookie when the previous one is expiring, and that's why you need to call `start` or `save` (we save some bandwidth for not writing the cookie on all requests).

What do you mean about `open` result being empty? Do you mean that `local session` is `nil` (can you write error log the exact type of that variable, it shouldn't ever be `nil`, and if it is, there is a bug)? Or that `session.data.nameId` is `nil`? That could be in case of client side cookie has expired, client side cookie is tampered, redis sessions have been flushed or expired, user agent has been changed, configs has been changed. And you have not configured this:

https://github.com/bungle/lua-resty-session#string-sessionsecret

or

```nginx
# Replace with your own secret
set $session_check_ssi 623q4hR325t36VsCD3g567922IC0073T;
```

If you don't provide that and have multiple Nginx servers or even multiple workers then it could be that they don't have the same secret. Now if the request is routed to a worker that has a different secret, the MAC checks will fail.

It can also be that Redis is timeouting, it could be that Redis locking timeouting. Well it can be multiple of things, and they all can fail.

**Comment by bungle** [comment]
This is not enabled anymore by default on 2.12.
